version: "3"
services:
  scraper:
    build: 
      context: .
      dockerfile: Dockerfile.scraper
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "6300:5000"
  redis:
    image: redis:5
